### ISSUE TITLE
Feature request: detect missing formatted message in attributes

### ISSUE THREAD

**Issue by longsleep** [calm/eslint-plugin-react-intl#1]
Certain attributes require also translation. This plugin is aweseome and it would be nice if it can be extended to also check for a certain set of attributes (maybe with configuration, which to check).

For example `label` and `aria-label` would be nice defaults.

What do you think?

**Comment by blainemuri** [comment]
Hey @longsleep, thanks for bringing this up! I'm definitely down to implement another option for additional html attributes.
Could you give some concrete examples of where the above attributes are being used so that I can better understand the issue as well?

**Comment by blainemuri** [comment]
It's a bit delayed, but I'm going to start work on adding in this feature today.

**Comment by longsleep** [comment]
> It's a bit delayed, but I'm going to start work on adding in this feature today.

Cool! For some examples see https://material-ui.com/components/checkboxes/#accessibility - checkboxes use various attributes in itself (which need translation) and also for accessibility a bunch of other general purpose human readable attributes are required.

**Comment by blainemuri** [comment]
Resolved by https://github.com/calm/eslint-plugin-react-intl/pull/8

@longsleep we currently don't use Material UI at Calm, so I haven't tested this with production code. However, I have written some basic tests around the new inputProps checking. Feel free to open up another issue if it's not working properly. I'll be available the rest of the week to fix any issues.

New options for missing-formatted-message include:
```
"enforceLabels": false,
"enforceImageAlts": false,
"enforceInputProps": false
```

EnforceInputProps will check for any nested props in the specific attribute `inputProps`. As of now it only checks `label` and `aria-label`, as those are the two most likely ones to be used for a13y. I didn't want to add in `title` since that is a more common attribute to pass in as an actual prop
