### ISSUE TITLE
String disallowed by linter

### ISSUE THREAD

**Issue by ghill-legwork** [calm/eslint-plugin-react-intl#9]
Hi,

I have the following:

```jsx
  <FormattedMessage id={`${prefix}.settings`} defaultMessage='Default message' />
```

But this causes a lint error of:

```
intl attributes must be strings eslint(@calm/react-intl/missing-attribute)
```
It's complaining about the `settings` id value. I thought that using JSX in this way would create a string, any thought as to why this isn't allowed?

Thanks.

**Comment by blainemuri** [comment]
Hey @ghill-legwork, when initially creating this I wanted to discourage variables/string interpolation for message IDs. The ID should be static so that you can guarantee the translation will be consistent. Not to say this is the only correct answer, it's just the stylistic choice we've chosen to follow at Calm.

I can see a use case for having prefixes linked exactly to a particular component, but that would also output the same string multiple times, one for each prefix. If this is the desired behavior I can add an option to disable that rule. Let me know your thoughts on this!

**Comment by ghill-legwork** [comment]
The request for this is just to have an option to remove repetition. 

```jsx
  const prefix = 'some.really.nested.organized.prefix.thats.reused';
  <FormattedMessage id={`${prefix}.settings`} defaultMessage='Default message' />
  <FormattedMessage id={`${prefix}.home`} defaultMessage='Default message' />
  <FormattedMessage id={`${prefix}.title`} defaultMessage='Default message' />
```

This would look really nasty without the prefix.

**Comment by blainemuri** [comment]
I think both of the options to disable defaultMessage and disable requiring id to be a string are valid. I should be able to get that out by this afternoon/tomorrow morning the latest.

For that last one I would love that feature, but unfortunately it's rather inefficient to solve in eslint. Since the abstract syntax tree doesn't store references to variables, we'd have to track those ourselves. And since variable declarations and props show up first in the AST, before they're used, we'd need to track all props within all components. This takes up quite a bit of memory, and on a small scale test it slowed down the linter quite a bit.

I'm still open to adding that feature as an option, but it's a larger task.

**Comment by ghill-legwork** [comment]
That sounds great. Thanks for looking at this.

**Comment by blainemuri** [comment]
https://github.com/calm/eslint-plugin-react-intl/pull/10

PR still needs to be reviewed, and it's Friday so I don't want to push anything today. Plan is to get this tested by peers and merged in on Monday.

**Comment by blainemuri** [comment]
https://github.com/calm/eslint-plugin-react-intl/pull/10
